### ISSUE TITLE
Home page jumbotron area: We'll need to add a small, subtle bouncing arrow to the lower left area of the jumbotron image. See comp for size/location: https://invis.io/KCU3HJWRX3T

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/Sargon-QA#10]
This was a client ask.

For the animation I'm thinking something like this: https://codepen.io/bewley/pen/revRQv

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved in the current build

**Comment by pguevara65** [comment]
@cmoosman1 thank you!

@jthiel16 can you please review?

cc: @NoelWormwood

**Comment by jthiel16** [comment]
Looks great, thank you
