### ISSUE TITLE
On both the "Stone" and "Steel" service pages, if you scroll down to the "Additional Services" section ... 

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/Sargon-QA#11]
The 4 images on the left side have been updated in WP, but are not showing up on the front end currently. This is happening for both the Steel and Stone pages:

https://drive.google.com/file/d/19B6uC0KGiKsOgDvaSLx0WSYWG19-xbPw/view?usp=sharing

**Comment by cmoosman1** [comment]
@pguevara65 - This is resolved in the current build

**Comment by pguevara65** [comment]
@NoelWormwood let me know if i can help review
