### ISSUE TITLE
Mobile nav bar

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/Sargon-QA#13]
This is not functioning as expected and is showing a white block in place of the hamburger menu.

Let's left-align the logo, with hamburger menu icon to the right of it.

I think we should also switch it to the mobile nav a bit earlier (like at 990px wide), because the phone number and contact us are getting cut off between 770 and 990.

https://drive.google.com/file/d/12AmfSWrTMHGjOJWnNcpAulpDkHmXvEtr/view?usp=sharing
https://drive.google.com/file/d/12Bwkh9txn6vCOjN1pwN5DnLxWttfnCwR/view?usp=sharing

Comment from Jason after submission:
The hamburger icon and the switch to mobile nav looks good.

But we have too much padding around the outside edges of both the logo and hamburger icon.

Let's tighten that up so there's about 15px from screen edge to both of those elements

https://drive.google.com/file/d/19C4vmdzpi3ElAuW520kkiq_uwJFWNog5/view?usp=sharing

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved in the current build

**Comment by pguevara65** [comment]
@cmoosman1 thank you!

@jthiel16 can you please review?

cc: @NoelWormwood

**Comment by jthiel16** [comment]
Looks good, thank you
