### ISSUE TITLE
Footer:

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/Sargon-QA#15]
On desktop, the logo needs more space between it and the "Services" column of text. Can we move "Services..." over to the right so it sits closer to the other column of text.

Then on mobile, the layout isn't working as comped. Was thinking everything would go to centered (using the stacked logo). We need to make sure to add some padding beneath the logo so it has some breathing room, and let's keep the social logos all on the same line.

WP Screengrabs:
https://drive.google.com/file/d/12T_BrJdndGLfXfaetQYztM2A75CQ_ERa/view?usp=sharing
https://drive.google.com/file/d/12Tb_Hgd-CM8ANusdJZyhkrjTCN2sof6x/view?usp=sharing

Comps for reference:
https://drive.google.com/file/d/12bVl1ndVj34GKEhXYsxf93FJPvjo0NjO/view?usp=sharing
https://drive.google.com/file/d/12_Qv1JMlddBGWWqNFEjzV5T2ymLHRs3p/view?usp=sharing

Jason's comment after submission:
Cool, all looks good except one minor thing:

When viewing on mobile, the logo looks just a tad off-centered.

https://drive.google.com/file/d/19K6YqSJSQuq2M7PtZittQHmRsjITpPPT/view?usp=sharing

**Comment by NoelWormwood** [comment]
@cmoosman1 all looks good except one minor thing:

When viewing on mobile, the logo looks just a tad off-centered.

https://drive.google.com/file/d/19K6YqSJSQuq2M7PtZittQHmRsjITpPPT/view?usp=sharing

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved I will msg when i push

**Comment by NoelWormwood** [comment]
@jthiel16 Please QA

**Comment by jthiel16** [comment]
Looks good, thank you
