### ISSUE TITLE
Home page Get a Quote form

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/Sargon-QA#21]
The "Submit" button styling is incorrect. Should be the same gold treatment as the rest of the pages

**Comment by cmoosman1** [comment]
@pguevara65 - This is resolved in the current build

**Comment by pguevara65** [comment]
@NoelWormwood let me know if you want me to review

**Comment by NoelWormwood** [comment]
@jthiel16 please review

**Comment by jthiel16** [comment]
Looks good
