### ISSUE TITLE
Universal Get a Quote Form

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/Sargon-QA#23]
1. Can we add auto-formatting to the phone number field

2. Can we use instant form validation (so that when user types an invalid email format or zip we let them know right away)

**Comment by pguevara65** [comment]
@NoelWormwood is this for the Partner With Us form? If not can you please provide the link for the Get A Quote form.

cc: @cmoosman1

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved in the current build
