### ISSUE TITLE
Employment page, the "Open Positions" container: 

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/Sargon-QA#24]
Let's reduce the height of this container when there are no entries listed. Right now there's a lot of extra space at the bottom

https://drive.google.com/file/d/19CB4byYBA6JBETo4LH8nd23l-xCbTnkR/view?usp=sharing

**Comment by cmoosman1** [comment]
@pguevara65 - This is resolved in the current build

**Comment by pguevara65** [comment]
@NoelWormwood let me know if you want me to review

**Comment by NoelWormwood** [comment]
@jthiel16 This looks good to me but please review as well.

**Comment by jthiel16** [comment]
Looks good, thanks!
