### ISSUE TITLE
There are some areas throughout the site where an image has been loaded to WP, but is not showing up on front end.

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/Sargon-QA#26]
2 specific spots I'm seeing:

1. Home page, the two "people" photos surrounding the gold testimonial quote area.

2. About Us page, in the "community involvement" section

3. Contact Us page, the 4-image quadrant

**Comment by cmoosman1** [comment]
@pguevara65 - This is resolved in the current build

**Comment by pguevara65** [comment]
@jthiel16 can you please review?

**Comment by jthiel16** [comment]
Looks good
