### ISSUE TITLE
CMS --> Front End Connection

### ISSUE THREAD

**Issue by NoelWormwood** [Tallwave/Sargon-QA#32]
The team has made a few different content/imagery changes within the CMS and not showing on the front end. Can we please ensure this is resolved across the full site.

**Comment by cmoosman1** [comment]
@NoelWormwood - Hey gotta give me a list here, Im pretty sure everything is wired up but if there is something not happening give me the page/section in this ticket.

**Comment by NoelWormwood** [comment]
The only two things I believe were the additional services images and circle icons. I will close this ticket and submit new tickets if we run across them.
