### ISSUE TITLE
Global - Card Images

### ISSUE THREAD

**Issue by NoelWormwood** [Tallwave/Sargon-QA#38]
On all pages the card images at the bottom of each page have been updated but are not pulling through to the CMS
<img width="1417" alt="Screen Shot 2019-10-16 at 8 22 32 AM" src="https://user-images.githubusercontent.com/39572221/66933562-1e3bc800-efee-11e9-8b39-c320a06511da.png">

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved in the current build

**Comment by NoelWormwood** [comment]
@cmoosman1 
Card Images on: Our work, about us and Employment do not match what is loaded into the CMS

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved in the current build
