### ISSUE TITLE
Featured Work Icon 

### ISSUE THREAD

**Issue by NoelWormwood** [Tallwave/Sargon-QA#39]
This is still too high...please lower to right above the next component
<img width="1424" alt="Screen Shot 2019-10-16 at 8 24 36 AM" src="https://user-images.githubusercontent.com/39572221/66933828-796dba80-efee-11e9-9f21-e6a467e9643f.png">

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved in the current build

**Comment by NoelWormwood** [comment]
@cmoosman1 This is still sitting high for me on both my laptop screen and larger monitor (see both screen shots below). @jthiel16 Can you confirm if this is the intended placement and it's just my screens or if we need to lower it more?

![Screen Shot 2019-10-16 at 10 48 39 AM](https://user-images.githubusercontent.com/39572221/66944793-bc398d80-f002-11e9-9caf-9e61f402c1cb.png)
<img width="1415" alt="Screen Shot 2019-10-16 at 10 48 28 AM" src="https://user-images.githubusercontent.com/39572221/66944796-be035100-f002-11e9-8470-96ce75858b3a.png">

**Comment by jthiel16** [comment]
@NoelWormwood Yes, looks like it's sitting a bit too high for me too, and the placement is tied to the height of the browser so I think that's why it's looking odd at certain browser widths. Intention is for it to sit about 80px above the bottom of the hero container.

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved I will msg in basecamp when I push
