### ISSUE TITLE
About Us Page, in the "Float Section" of the header ...

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/Sargon-QA#4]
In WP I'm not able to change the states icon image.

We need to update that to this file:
https://drive.google.com/file/d/1Qv9VERz6X3ap4WWqp0XwGBqZ555Kx-B0/view?usp=sharing

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved in the current build

**Comment by pguevara65** [comment]
@jthiel16 can you please review?

@cmoosman1 thank you!

cc: @NoelWormwood

**Comment by jthiel16** [comment]
Looks good, thank you
