### ISSUE TITLE
IE 11 Not Loading - - stuck on loading preview

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/Sargon-QA#41]
**What:**
The site is not loading on IE 11
http://sargonmc.wpengine.com/

IE version: 11.805.17763.0
Windows version: 10 Pro

What I see on IE 11:
![image](https://user-images.githubusercontent.com/46331985/66965511-c2456380-f02e-11e9-8a45-8c169420e3dd.png)

Expected Result that I see on Chrome:
![image](https://user-images.githubusercontent.com/46331985/66965529-d5f0ca00-f02e-11e9-8559-76492c1f40f1.png)

**Why:**
Per the SOW we support IE 11

**Timeline:**
n/a

**CC:**
@NoelWormwood

**Comment by cmoosman1** [comment]
@NoelWormwood @pguevara65 - This is resolved in the current build

**Comment by pguevara65** [comment]
@cmoosman1 @NoelWormwood thank you! I see it
