### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/Sargon-QA#42]
**What:**
Please add a favicon
http://sargonmc.wpengine.com/

**Why:**
It is a common website practice.

cc: @NoelWormwood 

Thanks!

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved in the current build

**Comment by pguevara65** [comment]
@cmoosman1 I cleared cache & went incognito but I'm not seeing it.

**Comment by cmoosman1** [comment]
@pguevara65 - On IE 11 (any Win OS) custom favicon will not load without a valid https cert. Right now we are using the dev mode of WPEngine so we dont have a valid cert in place.
