### ISSUE TITLE
Home page, logo section

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/Sargon-QA#6]
The spacing looks off, both horizontally and vertically, and especially when Im looking at it at smaller/responsive sizes, the logos become off-center and start crashing into each other.

Can we space the logos out more horizontally, and keep everything centered vertically within the white divider area?

The logos also look low quality. Recommend using the 2x image files for better quality.

Example screengrabs:
https://drive.google.com/file/d/125qGJsFlFzpPWlG0F7frWyAFwZq9sZpP/view?usp=sharing
https://drive.google.com/file/d/125qGJsFlFzpPWlG0F7frWyAFwZq9sZpP/view?usp=sharing

@jthiel16  commented after submission: 
FYI, we swapped out logo files for the 2x versions, so the quality issue is resolved. The spacing issue remains

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved will msg when I push

**Comment by NoelWormwood** [comment]
@jthiel16 Please QA

**Comment by jthiel16** [comment]
Looks good, thank you
