### ISSUE TITLE
SEO Fixes

### ISSUE THREAD

**Issue by NoelWormwood** [Tallwave/Sargon-QA#67]
- [x] htaccess, redirects www trailin/ and 404

- [x] canonical fix

**Comment by NoelWormwood** [comment]
Feedback from Criss:

The issues/concerns brought up today have been resolved.

- Meta data/canonical prepended with sargonmc.com
- www redirects i.e. https://www.sargonmc.com/sitemap.xml now goes to https://sargonmc.com/sitemap.xml  the same will apply to robots.txt
- Trailing slash redirect to current page https://www.sargonmc.com/our-work/ resolves to https://www.sargonmc.com/our-work

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved in Production
