### ISSUE TITLE
Maintenance Page

### ISSUE THREAD

**Issue by NoelWormwood** [Tallwave/Sargon-QA#69]
- Comp: https://invis.io/YZUEZTOVWQ7
 - Copy: https://docs.google.com/document/d/1JMxB7VRNZHEySAi6BWFwbN7G0ESZoAlPe8_IWWZ2J14/edit?ts=5d9f7d5b# (page 16)

**Comment by NoelWormwood** [comment]
@cmoosman1 This has been approved by the client. Can you please confirm we have push this live by EOD tomorrow 11/27

**Comment by cmoosman1** [comment]
@NoelWormwood - This is completed.
