### ISSUE TITLE
The main nav bar should disappear when scrolling downward, and then reappear when user starts scrolling back up, from anywhere on the page

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/Sargon-QA#7]
See castlehotsprings.com for example

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved in the current build

**Comment by pguevara65** [comment]
@cmoosman1 thank you!

@jthiel16 can you please review?

cc: @NoelWormwood

**Comment by jthiel16** [comment]
Looks great, thank you
