### ISSUE TITLE
UPDATE 10/22: Removal of title bar/icons

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/Sargon-QA#9]
https://drive.google.com/file/d/13Cs84EAN0pCSsWlO973LNiwo48bxRhfH/view?usp=sharing

**Comment by cmoosman1** [comment]
@pguevara65 - This is resolved in the current build

**Comment by NoelWormwood** [comment]
@jthiel16 Please review

**Comment by jthiel16** [comment]
1) Can we left-align these modules to the same spot as the text heading just beneath it, at all sizes
2) Employment page is missing this element. Suggest using the same icon as About Us
3) Masonry/Steel/Stone pages are using a white icon for the selected page (let's make that black) 
4) These icons on the Masonry/Steel/Stone pages were intended to be links to the other pages, but it's missing that functionality. Hover states are in page 1 of UI kit.

**Comment by NoelWormwood** [comment]
@jthiel16 This ticket is for the internal title icons. Can we add the size adjustment requests here instead of creating a new ticket based upon our convo this morning.

**Comment by jthiel16** [comment]
@NoelWormwood @cmoosman1 Yeah, one additional thing to add to this list:

5. The "header-icons-wrapper" div is appearing a bit too large and prominent. Let's reduce the height of that element on all interior pages, so it's at most 60px high

**Comment by NoelWormwood** [comment]
@jthiel16 Please QA

**Comment by jthiel16** [comment]
@NoelWormwood @cmoosman1 

1. Can we left-align these modules to the same spot as the text heading just beneath it, at all sizes
2. Employment page is missing this element. Suggest using the same icon as About Us
3. Masonry/Steel/Stone pages are using a white icon for the selected page (let's make that black)
4. These icons on the Masonry/Steel/Stone pages were intended to be links to the other pages, but it's missing that functionality. Hover states are in page 1 of UI kit.
5. The "header-icons-wrapper" div is appearing a bit too large and prominent. Let's reduce the height of that element on all interior pages, so it's at most 60px high

**Comment by NoelWormwood** [comment]
@cmoosman1 The Sargon team has decided that they would like to remove all page title bar/icons across the site.

Services page (Steel, Masonry, Stone)
About Us
Contact Us

**Comment by cmoosman1** [comment]
@NoelWormwood - This is resolved in the current build

**Comment by pguevara65** [comment]
@jthiel16 can you please review?

@cmoosman1 thanks!
cc: @NoelWormwood

**Comment by jthiel16** [comment]
Thanks Criss, closing the ticket
